---
name: Push README

on:
  push:
    paths:
      - "README.md"
      - "README-containers.md"
      - ".github/workflows/container_description.yml"
    branches:
      - 'main'
      - 'master'

jobs:

  PushDockerHubReadme:
    name: Push README to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Set docker hub repo name
        run: echo "DOCKER_REPO_NAME=$(DOCKER_REPO=${{ secrets.DOCKER_HUB_ORG }} make docker-repo-name)" >> $GITHUB_ENV

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
        with:
          destination_container_repo: ${{ env.DOCKER_REPO_NAME }}
          provider: dockerhub
          short_description: ${{ env.DOCKER_REPO_NAME }}
          readme_file: ''
