---
name: Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  Release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "${TAG}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${TAG#v} / $(date '+%Y-%m-%d')"

  Build:
    name: Build Release
    runs-on: ubuntu-latest
    needs:
      - 'Release'
    permissions:
      contents: read
    strategy:
      matrix:
        thread: [ 0, 1, 2 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CI Commands
        uses: rebelmediausa/promci@v1

      - name: Run Build
        uses: ./.github/promci/actions/build
        with:
          promu_codesign_binary: minecraft_exporter
          parallelism: 3
          thread: ${{ matrix.thread }}

  Publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs:
      - 'Build'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CI Commands
        uses: rebelmediausa/promci@v1

      - name: Publish Release
        uses: ./.github/promci/actions/publish_release
        with:
          image_name: minecraft-exporter
          image_arch: linux/amd64,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x
          docker_hub_organization: ${{ secrets.DOCKER_HUB_ORG }}
          docker_hub_login: ${{ secrets.DOCKER_HUB_LOGIN }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
