---
name: Create Tag

on:
  push:
    branches: [ master ]

jobs:

  Tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set tag ENV
        run: |
          echo "VERSION=v$(cat VERSION)" >> $GITHUB_ENV

      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.VERSION }}',
              sha: context.sha
            })