---
name: Test & Build

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CI Commands
        uses: rebelmediausa/promci@v1

      - name: Setup Environment
        uses: ./.github/promci/actions/setup_environment

      - name: Download Go mods
        run: go mod download

      - name: Run make command
        run: make

      - name: Remove binary
        run: make remove-binary

      - name: Git DIFF
        run: git diff --exit-code

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Test]
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        thread: [ 0, 1, 2 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CI Commands
        uses: rebelmediausa/promci@v1

      - name: Run Build
        uses: ./.github/promci/actions/build
        with:
          promu_codesign_binary: minecraft_exporter
          parallelism: 3
          thread: ${{ matrix.thread }}
